[package]
name = "corm_state"
edition = "2024.beta"

[environments]
localnet = "5b035e1b"
stillness = "4c78adac"
testnet_stillness = "4c78adac"
utopia = "4c78adac"
testnet_utopia = "4c78adac"

[dependencies]
corm_auth = { local = "../corm_auth" }
